[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10


[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/sycrw"
  weight = 10

