colorScheme = "Ocean"

mainSections = ["posts", "projects"]


[homepage]
    layout = "background"
    homepageImage="images/hero.webp"
    showrecent = true

[author]
    name = "Tim Kausemann"
    headline = "Software Developer"
    image = "images/author.jpg"
    links = [
        { github = "https://github.com/sycrw" },
        { linkedin = "https://www.linkedin.com/in/tim-martin-kausemann-478b44265/" },

    ]

