colorScheme = "Ocean"


[homepage]
    layout = "background"
    homepageImage="images/hero.webp"
    showrecent = true
    cardView = true

[author]
    name = "Tim Kausemann"
    headline = "Software Enthusiast"
    image = "images/author.jpg"
    bio = "A soon to be student a the Technische Universität München studying informatiks(computer science). Meanwhile i am also a working student a Check24."
    links = [
        { github = "https://github.com/sycrw" },

    ]